---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: item-deployment
    labels:
        app: feedme
spec:
    replicas: 1
    selector:
        matchLabels:
            app: item
    template:
        metadata:
            labels:
                app: item
        spec:
            containers:
                - name: item
                  image: feedme/item:latest
                  imagePullPolicy: Never
                  env:
                      - name: REDIS_ADDR
                        value: localhost:6379
                      - name: MYSQL_DSN
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: mysql_dsn

---
apiVersion: v1
kind: Service
metadata:
    name: item-service
    labels:
        app: feedme
spec:
    type: LoadBalancer
    ports:
        - port: 3000
          targetPort: 3000
    selector:
        app: item
