---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: apigw-deployment
    labels:
        app: feedme
spec:
    replicas: 1
    selector:
        matchLabels:
            app: apigw
    template:
        metadata:
            labels:
                app: apigw
        spec:
            containers:
                - name: apigw
                  image: feedme/apigw:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  env:
                      - name: PORT
                        value: "3000"
                      - name: UPDATES_ADDR
                        value: updates:3001
                      - name: USER_ADDR
                        value: user:3002
                      - name: REDIS_ADDR
                        value: localhost:6379
                      - name: BASE_URL
                        value: localhost:8080
                      - name: GOOGLE_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: google_client_id
                      - name: GOOGLE_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: google_client_secret
                      - name: SERVER_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: server_secret

---
apiVersion: v1
kind: Service
metadata:
    name: apigw-service
    labels:
        app: feedme
spec:
    type: LoadBalancer
    ports:
        - port: 3000
          targetPort: 3000
    selector:
        app: apigw
