apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: selfsigned-cert
    namespace: app
spec:
    dnsNames:
        - api.feedme.benosborn.tech
    secretName: selfsigned-cert-tls
    issuerRef:
        name: test-selfsigned
